### ISSUE TITLE
[CLIENT-FEAT-REQ] Tab Shows EvieClient Logo

### ISSUE THREAD

**Issue by JustPurpleN** [EvieClient/EvieClient-Releases#8]
Add a EvieClient Logo when you click tab for everyone using EvieClient. (Like Lunar and Badlion have it) 

To add this when you click tab.

**Comment by tristancamejo** [comment]
Was going to add this, just need to update https://github.com/twisttaan/eviesocket to be more reliable.

**Comment by JustPurpleN** [comment]
> Was going to add this, just need to update https://github.com/twisttaan/eviesocket to be more reliable.

Ok, Thank you! (Btw the link https://github.com/twisttaan/eviesocket shows a 404 Error)

**Comment by tristancamejo** [comment]
It's a private repo. But basically the socket server is what's used for communicating with Evie's API really quickly instead of using the rest api. It's main purpose is seeing if someone is currently using Evie Client as it responds nearly instantly, only problem is that it's not as accurate at the moment as it says people that have  used evie client before are on it.

**Comment by JustPurpleN** [comment]
> It's a private repo. But basically the socket server is what's used for communicating with Evie's API really quickly instead of using the rest api. It's main purpose is seeing if someone is currently using Evie Client as it responds nearly instantly, only problem is that it's not as accurate at the moment as it says people that have used evie client before are on it.

Ah, ok
